title: "Deep Learning: Segmentación de Células e Interpretación de Texto"
author: "Mateo Gomez, Mateo Molinares, David Ibañez y Alejandro Moya"
logo: logo.png

execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

html:
  use_issues_button: false
  use_repository_button: false
